@baseUrl = http://127.0.0.1:8000/category

### Get all category + products
GET {{baseUrl}}/get


### add new category
POST {{baseUrl}}/new
Content-Type: application/json

{
    "name":"Burger",
    "ref":"#123",
    "description":"burger description",
    "tags":["pain","viande"],
    "thumbnail":"https://picsum.photos/seed/picsum/200/300",
    "afficher": true
}


### delete a category

DELETE {{baseUrl}}/remove
Content-Type: application/json

{
    "id":"6485f838a554602ad1d4a6ab"
}

### edit category
PUT {{baseUrl}}/edit
Content-Type: application/json

{
    "id":"6485d7c1d3c5a2eb8181e269",
    "ref":"#123",
    "description":"burger description",
    "tags":["pain","viande"],
    "thumbnail":"https://picsum.photos/seed/picsum/200/300",
    "afficher": true
}


### sort category
PATCH {{baseUrl}}/sort
Content-Type: application/json

{
    "id":"6485d7ffd3f3646641119932",
    "moveTo":"2"
}