### add new category
POST http://127.0.0.1:8000/product/new
Content-Type: application/json

{
    "category_id":"648f23a353121a213dfe54e7",
    "name":"Rosti chicken",
    "skus":["648f2ead33bcaf9df1fef3ca"],
    "afficher": true,
    "ref":"Rosti chicken",
    "thumbnail":"https://picsum.photos/seed/picsum/200/300"
}