### add new category
POST http://127.0.0.1:8000/sku/new
Content-Type: application/json

{
    "price":10,
    "afficher": true,
    "option_list_ids":["648f2e5333bcaf9df1fef3c0","648f2e6833bcaf9df1fef3c4"],
    "name":"Menu",
    "ref":"multi"
}