### add new category
POST http://127.0.0.1:8000/option/new
Content-Type: application/json

{
    "price":0,
    "afficher": true,
    "defaultValue": true,
    "name":"Jambon cuit",
    "ref":"Jambon_cuit"
}