### add new category
POST http://127.0.0.1:8000/category/new
Content-Type: application/json

{
      "ref": "formules",
      "name": "Formules",
      "description": "Catégorie regroupant les formules",
      "thumbnail": "https://picsum.photos/seed/picsum/200/300",
      "afficher": true
}